version: '3'

services:
  python:
    build: .
    command: ["python","/app/process.py"]
    volumes:
      - $PWD/process.py:/app/process.py
      - $PWD/file.yml:/app/file.yml
    environment:
      - GH_APP_ID=${GH_APP_ID}
      - GH_APP_KEY_B64=${GH_APP_KEY_B64}
      - GH_ORGANISATION=${GH_ORGANISATION}
      - YML_FILE=/app/file.yml
    