name: Process

on:
  workflow_dispatch:
  push:

jobs:
  process:
    runs-on: ubuntu-latest
    # container:
    #  image: python:3.12.3-slim-bookworm

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12.3' 

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Process
        run: python process.py
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_KEY_B64: ${{ secrets.GH_APP_KEY_B64 }}
          GH_ORGANISATION: 'base2cloud'
          YML_FILE: './file.yml'
      
      - name: Check changes
        run: |
          git diff file.yml || echo
          git status --untracked-files=no | grep modified | grep -q file.yml && echo "MODIFIED=YES">> $GITHUB_ENV || echo "MODIFIED=NO">> $GITHUB_ENV

      - name: Pull request
        if: ${{ env.MODIFIED == 'YES' }}
        run: ./devops-bot.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
